### PR TITLE
Franz  lions data passing

### PR DESCRIPTION
**Pull request by Znarfois**
- [x] Get data from orgs.json
- [x] Display Orgs based on cluster

### CODE REVIEW

**Review by Hjkun77 — APPROVED** [review]
Looks good merge UI PR first and then git pull after that fix `organisations` to `organizations`

**Comment by Jansalvador1445** [comment]
Looks good but conflicts

**Comment by Jansalvador1445** [comment]
Fixed Conflicts. Ready to merge

**Comment by Znarfois** [comment]
> Fixed Conflicts. Ready to merge

Thank you, sir!

**Review by Hjkun77 — APPROVED** [review]

**Pull request merged**
